### ISSUE TITLE
Half of the Python scripts are failing under opinel 3.x

### ISSUE THREAD

**Issue by grettir** [nccgroup/AWS-recipes#11]
`requirements.txt` specifies a need for `opinel>=3.0.11,<4.0.0`,  but about half of the Python scripts still haven't been updated to support 3.x.

Here's a list of the older scripts that are failing under 3.x:

```
aws_cloudtrail_enable_all_regions.py
aws_cloudtrail_get_logs.py
aws_ec2_empty_default_security_groups.py
aws_iam_create_default_groups.py
aws_iam_create_policy.py
aws_iam_create_user.py
aws_iam_rotate_my_key.py
aws_iam_sort_users.py
```

**Comment by l01cd3v** [comment]
Thanks, I'll work on these.

**Comment by l01cd3v** [comment]
I think that I'm going to remove the aws_cloudtrail_enable_all_regions because it doesn't really make much sense given that multi region trails exist now.

**Comment by l01cd3v** [comment]
aws_cloudtrail_get_logs.py should work already, it was renamed to ./awsrecipes_get_cloudtrail_logs.py

**Comment by l01cd3v** [comment]
This actually requires a new version of opinel, which I'll publish once all scripts are fixed

**Comment by l01cd3v** [comment]
closing
