### ISSUE TITLE
Default JSON Policy out of date.

### ISSUE THREAD

**Issue by stephenviola** [nccgroup/AWS-recipes#24]
The default policy needs two new permissions.

**Comment by stephenviola** [comment]
"cloudtrail:GetEventSelectors",
"elasticloadbalancing:DescribeLoadBalancerPolicies",

**Comment by stephenviola** [comment]
An error occurred (AccessDenied) when calling the DescribeLoadBalancerPolicies operation: User: arn:aws:iam::XXXXXXXXXXXX:user/service.aws-scout is not authorized to perform: elasticloadbalancing:DescribeLoadBalancerPolicies

An error occurred (AccessDeniedException) when calling the GetEventSelectors operation: User: arn:aws:iam::XXXXXXXXXXXX:user/service.aws-scout is not authorized to perform: cloudtrail:GetEventSelectors on resource: arn:aws:cloudtrail:us-east-1:917848291101:trail/shared-services-trail

**Comment by x4v13r64** [comment]
It is no longer recommended to use a customer managed policy. Please refer to https://github.com/nccgroup/scout2#aws-credentials
