### ISSUE TITLE
Scripts are broken after recent update of opinel

### ISSUE THREAD

**Issue by ops-usrp** [nccgroup/AWS-recipes#5]
aws_recipes_init_sts_session.py", line 6, in <module>
   from opinel.utils_sts import *
ImportError: No module named utils_sts

**Comment by l01cd3v** [comment]
Sorry about that, I forgot to push the corresponding code changes.

**Comment by l01cd3v** [comment]
init_sts_session and assume_role should be working now. I'll leave the issue open until I fix all the other scripts too

**Comment by l01cd3v** [comment]
Should be all good now
