### ISSUE TITLE
aws_iam_rotate_my_key.py script looking for obsolete opinel.utils_sts

### ISSUE THREAD

**Issue by grettir** [nccgroup/AWS-recipes#6]
It looks like the `aws_iam_rotate_my_key.py` script is still looking for `opinel.utils_sts`, which was last included in opinel 0.24.5, resulting in:

```
Traceback (most recent call last):
   File "./aws_iam_rotate_my_key.py", line 6, in <module>
   from opinel.utils_sts import *
ImportError: No module named utils_sts
```

**Comment by l01cd3v** [comment]
Thanks, I think this should work now

**Comment by l01cd3v** [comment]
I actually need to change more code... working on it

**Comment by l01cd3v** [comment]
Ok, should be good now - Make sure you update opinel too
