### ISSUE TITLE
opinel 3.0.0 breaks aws_recipes_create_ip_ranges.py

### ISSUE THREAD

**Issue by grettir** [nccgroup/AWS-recipes#9]
It looks like opinel 3.0.0 broke the `aws_recipes_create_ip_ranges.py` script (which is probably to be expected on major upgrades). Specifically, opinel's `handle_truncated_response()` now requires three arguments instead of four.

Here's the error that is generated:

```py
Fetching public IP information for the 'xxxxxxxx' environment...
...in ap-northeast-1: EC2 instances
Traceback (most recent call last):
  File "/xxxxxxx/AWS-recipes/Python/aws_recipes_create_ip_ranges.py", line 221, in <module>
    sys.exit(main(args))
  File "/xxxxxxx/AWS-recipes/Python/aws_recipes_create_ip_ranges.py", line 149, in main
    reservations = handle_truncated_response(ec2_client.describe_instances, {}, 'NextToken', ['Reservations'])
TypeError: handle_truncated_response() takes exactly 3 arguments (4 given)

```

Again, thanks for all of your work. I use these scripts (along with Scout2) on nearly a daily basis and they make my life *so* much more pleasant.

**Comment by l01cd3v** [comment]
Yes it does; opinel 3.0.0 is actually still an RC and has not been integrated with any code besides the dev branch of Scout2.

The requirements files for both Scout2 and the AWS-recipes should specify the max version of opinel to be 1.5. Did you install it manually or did I mess up one of the requirements files?

**Comment by l01cd3v** [comment]
This should have been fixed. Note the new name with now underscore between aws and recipes:

awsrecipes_create_ip_ranges.py
